# netlify.toml

[build]
  command = "CI=false npm run build"  # Added CI=false to prevent treating warnings as errors
  publish = "build"
  functions = "netlify/functions"

# Redirect all requests for /api/* to the Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
