# netlify.toml

[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Redirect all requests for /api/* to the Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
